### ISSUE TITLE
Использование в другом проекте

### ISSUE THREAD

**Issue by mihdan** [sokolnikov911/yandex-turbo-pages#1]
Добрый день, могу ли я использовать ваши наработки внутри [своего плагина](https://github.com/mihdan/mihdan-yandex-turbo-feed) для WordPress, который создает ленту для турбо-страниц?

Есть какие-то требования или определённая лицензия?

Не увидел в классе, может ли он генерить тег img для header айтема.

**Comment by sokolnikov911** [comment]
@mihdan, добрый. Да я подписал MIT лицензией, поэтому смело используйте. Как генерить хедер вместе с img можно посмотреть в [этом примере](https://github.com/sokolnikov911/yandex-turbo-pages/blob/master/examples/turboContent.php).

**Comment by mihdan** [comment]
Спасибо
