### ISSUE TITLE
Добавить обработку блоков

### ISSUE THREAD

**Issue by KarelWintersky** [sokolnikov911/yandex-turbo-pages#11]
```
Channel -> yandex:logo
Channel -> lastBuildDate
Channel -> turbo:analytics type="custom" url=""
Channel -> ttl
Channel -> image (url, title, link)

Item -> guid
Item -> pdalink
item -> yandex:genre
item -> yandex:full-text
```

ну, как вариант, передайте ownership репозитория, у нас сейчас активно оно используется, допилю.

**Comment by sokolnikov911** [comment]
> ну, как вариант, передайте ownership репозитория, у нас сейчас активно оно используется, допилю.

Делайте PR, я посмотрю.

**Comment by KarelWintersky** [comment]
За 9 месяцев я уже и забыл что хотел...

Вспомню - добавлю/сделаю.

**Comment by seyitahmettanriver** [comment]
**PHP Version: 7.3**

```
[10-Feb-2021 07:03:42 UTC] PHP Fatal error:  Uncaught Error: Class 'Feed' not found in /home/website/public_html/a.php:6
Stack trace:
#0 {main}
  thrown in /home/website/public_html/a.php on line 6
```

**Comment by KarelWintersky** [comment]
@seyitahmettanriver , вы класс то подключили? И почему сюда?

**Comment by seyitahmettanriver** [comment]
Yes sorun çözüldü

10 Şub 2021 Çar 18:17 tarihinde Karel Wintersky <notifications@github.com>
şunu yazdı:
